### ISSUE TITLE
Allow disabling collections

### ISSUE THREAD

**Issue by treyhunner** [darrenburns/posting#103]
And I see the collection browser is open. I can manually run the "toggle collection browser" command to hide it, but it would be nice to hide/disable collections in startup via a configuration.

---

Relatedly, whenever I start posting I also see this error:

![image](https://github.com/user-attachments/assets/49f5a061-fc54-41fa-8dcc-7cf4cef72d5a)

It would be nice to not show that error no startup as well.

**Comment by darrenburns** [comment]
I've added a config in `1.13.0` for hiding/showing the collection browser on startup and also removed that pop-up message completely.
