### ISSUE TITLE
Feature Request: Scripts to update env variables and reload them

### ISSUE THREAD

**Issue by leobardomck** [darrenburns/posting#107]
Let me start by saying this is an awesome tool and looking forward to it's evolution.

Basically what I'm looking for is the same postman  feature of when calling a getToken api i can via script update the value of a variable and all of my request that need that variable will reloaded automatically instead of me having to add a new Authentication Header manually every time.

**Comment by darrenburns** [comment]
Thank you! This is pretty near the top of my priorities - hoping it'll arrive this year!

**Comment by darrenburns** [comment]
This was added in Posting 2 a while back. Let me know if you give at a shot!
