### ISSUE TITLE
Promote `uvx` as an Alternative to `uv tool install` for Posting

### ISSUE THREAD

**Issue by HomerusJa** [darrenburns/posting#122]
Before saying anything here, I love that you are recommending `uv` as the installation method!

## Background
In the groundbreaking release post of uv in August 2024, they use posting as the example for using their new `uvx` interface. In fact, this is how I found out about posting. See [here](https://astral.sh/blog/uv-unified-python-packaging#tools).

Currently, the documentation recommends using `uv tool install` for installing posting. However, `uvx` (alias for `uv tool run`) offers several advantages that could benefit users.

## Proposal
I propose we promote `uvx` as an alternative method for using posting, alongside the existing `uv tool install` recommendation.

## Benefits of Using `uvx` over `uv tool install`

1. **On-Demand Execution**: `uvx` allows users to run posting without a permanent installation, ideal for occasional use or trying out different versions.

2. **Reduced System Clutter**: Unlike `uv tool install`, `uvx` doesn't permanently install tools, keeping the system cleaner and saving disk space.

3. **Automatic Updates**: Each `uvx` run uses the latest version of posting, ensuring users always have the most recent features and bug fixes without manual updates.

4. **Version Flexibility**: Users can easily run different versions of posting without managing multiple installations, perfect for testing or specific project requirements.

5. **Simplified Workflow**: For users who prefer a "run-and-forget" approach, `uvx` eliminates the need to manage installations and uninstallations.

6. **Consistent Isolation**: `uvx` always runs posting in a fresh, isolated environment, preventing potential conflicts with other installed packages.

7. **Resource Efficiency**: While `uvx` caches installations, it doesn't consume permanent disk space for infrequently used tools.

## Implementation
To implement this change, we could:

1. Update the documentation to include `uvx` as an alternative method alongside `uv tool install`.
2. Provide examples demonstrating how to use posting with both `uvx` and `uv tool install`.
3. Explain the scenarios where each method might be preferable.

## Conclusion
Promoting `uvx` as an alternative to `uv tool install` for posting would provide users with greater flexibility and efficiency. This change could enhance user experience, particularly for those who prefer on-demand tool execution or want to minimize system clutter.

What are your thoughts on this proposal? I'm open to any feedback or suggestions for improvement. If wanted, I could create a pull request regarding this in no time...

**Comment by darrenburns** [comment]
Thanks for the suggestion - but I'm just going to stick with the `uv tool install` workflow for now. I'm likely going to rewrite the installation stuff fairly soon, and might throw in a sentence about `uvx` there.
