### ISSUE TITLE
got an unexpected keyword argument 'items'

### ISSUE THREAD

**Issue by diegoulloao** [darrenburns/posting#15]
I've just installed it, getting an error when opening the app: `posting`.

<img width="1133" alt="Screenshot 8" src="https://github.com/darrenburns/posting/assets/45423661/902b32e1-9766-4477-952a-c079bff9bc89">

macos
kitty terminal
python 3.12.3

**Comment by darrenburns** [comment]
Whoops! My bad.

1.0.0b39 was broken - I've yanked that release. 1.0.0b40 should fix the issue.

**Comment by diegoulloao** [comment]
thanks! I'll give it a try, first impression is looking very good!
It is possible to create a custom theme?

**Comment by darrenburns** [comment]
Custom themes aren't possible yet but they will come soon

**Comment by diegoulloao** [comment]
> Custom themes aren't possible yet but they will come soon

may not be difficult to implement, right? a theme directory can be assigned for import the files, those files could export this data format: https://github.com/darrenburns/posting/blob/8da732112d7323bbad3e988adb84a925df6b5466/src/posting/app.py#L559

I've created themes for some well-known terminal apps. I'd like to create a port of my neofusion theme for posting.

**Comment by darrenburns** [comment]
Yup, should be pretty straightforward 🙂

This feature will probably arrive this week or next week.
