### ISSUE TITLE
--collection . (for current dir) not working as expected

### ISSUE THREAD

**Issue by diegoulloao** [darrenburns/posting#17]
When I try to open the current directory in this way:
`posting --collection .`

It doesn't work as expected, it seems like the collection is not detected at all besides the first letter of the first folder is missing:
<img width="479" alt="Screenshot 11" src="https://github.com/darrenburns/posting/assets/45423661/583370d2-8a4f-49a2-84e5-836d0ed4ee09">

Tree:
<img width="397" alt="Screenshot 12" src="https://github.com/darrenburns/posting/assets/45423661/3e5ab56c-8754-4c60-8a54-c1f04ac4ae56">

Steps to reproduce:
1. Navigate into any collection directory. e.g. `cd ~/posting/my-collection`
2. Run `posting --collection .`

Expected result:
Get the ui info and folders name working ok same like just running `posting --collection ~/posting/my-collection`

<img width="476" alt="Screenshot 13" src="https://github.com/darrenburns/posting/assets/45423661/ce2c99fa-50cf-4250-8a8f-ef3a8a459dcb">

This is very useful in cases is easier to navigate into a collection folder just executing a preset alias like:
`alias post="posting --collection ."` for rapid access.

Latest version `v1.0.0b41`

**Comment by diegoulloao** [comment]
P.S: Nice work BTW, I'm loving this TUI app!

**Comment by darrenburns** [comment]
Thank you!

Fixed in `1.0.0b42`. Let me know if you hit any other issues!

**Comment by diegoulloao** [comment]
> Thank you!
> 
> Fixed in `1.0.0b42`. Let me know if you hit any other issues!

Sure! Thanks for the quick fixes.

**Comment by diegoulloao** [comment]
I've just tested. Working good!
