### ISSUE TITLE
Default collection is not working anymore

### ISSUE THREAD

**Issue by diegoulloao** [darrenburns/posting#19]
Is default collection not going anymore? I'm getting an error when executing the `posting` command from an arbitrary directory. I'm not sure if you removed the default collection logic or is a bug caused by the latest changes for #17. I've double checked the readme thinking you could've changed something in the `v1.0.3` release, but I can see that the info about the default collection is still there.

<img width="639" alt="Screenshot 14" src="https://github.com/darrenburns/posting/assets/45423661/85e405f7-ddba-43bc-984e-1bdc2c8a8d31">

**Comment by diegoulloao** [comment]
Derived of changes for #16

**Comment by darrenburns** [comment]
I can't reproduce this on my end. Can you share more information? What OS are you on, etc.

It looks like it might be a permissions issue - but the error message is slightly confusing to me.

Could you also run `posting locate collection` and then check that directory to see if it exists, if anything is inside it, and the permissions on it to ensure Posting can read from it?

**Comment by diegoulloao** [comment]
Oh, my bad, I closed the tab and opened a new one, it started to working again.
Omit this 🙏🏻
