### ISSUE TITLE
shift+k not moving back to first request group in collections widget

### ISSUE THREAD

**Issue by diegoulloao** [darrenburns/posting#21]
`shift+j` and `shift+k` provides actions to jump between request groups, it seems to work good except when trying to jump back to the first group. Pressing `shift+k` doesn't call the action for some reason, it smells like a tuple indexes issue, just saying

https://github.com/darrenburns/posting/assets/45423661/391c471e-a372-4a49-a29e-ca7c2b81545e

**Comment by darrenburns** [comment]
Thanks - fixed in `1.0.4`!
