### ISSUE TITLE
unicode characters in response body

### ISSUE THREAD

**Issue by breakstring** [darrenburns/posting#31]
https://github.com/darrenburns/posting/blob/7b1d0ae86d2990fa89d52b612284af3aaf590b55/src/posting/widgets/response/response_area.py#L80

In some JSON-type API requests, the returned content may contain Unicode characters, it will show as '\uxxx....' and making the response body unreadable.
Maybe, will you please add an 'ensure_ascii=False' parameter in json.dumps to resolve this kind of issue?
![WX20240712-103044](https://github.com/user-attachments/assets/7844c13d-7863-48b5-9593-b1bf732eb794)

**Comment by darrenburns** [comment]
Thanks for the report! Fixed in `1.1.0`: https://github.com/darrenburns/posting/releases/tag/1.1.0
