### ISSUE TITLE
Adding a support for gRPC would be really great.

### ISSUE THREAD

**Issue by JiraPit** [darrenburns/posting#36]
Considering that this is already very useful for server-to-server testing, adding a support for gRPC would be really great.

**Comment by darrenburns** [comment]
Sorry, this isn't going to happen any time soon. I want to keep Posting focused on HTTP for the foreseeable future.

**Comment by KirkEasterson** [comment]
> Sorry, this isn't going to happen any time soon. I want to keep Posting focused on HTTP for the foreseeable future.

Has this stance changed since your post? I would be interested in contributing to make this possible.
