### ISSUE TITLE
Some colors don't change when using a custom theme

### ISSUE THREAD

**Issue by diegoulloao** [darrenburns/posting#62]
Hey, I've tried my own custom theme, I can see some colors are breaking the palette, probably they aren't linked to the custom theme colors provided by the file.

`../themes/custom-theme.yml`

```yml
name: neofusion
primary: "#fd5e3a"
secondary: "#35b5ff"
accent: "#66def9"
background: "#06101e"
surface: "#052839"
error: "#fd5e3a"
success: "#35b5ff"
warning: "#e8e5b5"
```

**Screenshot:**
<img width="1440" alt="Screenshot 4" src="https://github.com/user-attachments/assets/6df3074b-36c3-4281-a20d-05c5a3aa6030">

**Comment by darrenburns** [comment]
Good spot - I've still to update those to pull from the theme - they require a little bit extra work. Even the builtin themes don't modify those colors at the moment.

**Comment by darrenburns** [comment]
The response status code now pulls the `$success`, `$warning` and `$error` colours from the theme.

**Comment by diegoulloao** [comment]
> The response status code now pulls the `$success`, `$warning` and `$error` colours from the theme.

<img width="1440" alt="Screenshot 4" src="https://github.com/user-attachments/assets/65ca3f6f-3974-481d-9b8e-39d052ac31e5">

The green one? Not seeing the colors reflected yet.

**Comment by darrenburns** [comment]
That's because I forgot to actually publish the release to PyPI 😂 

It's in `1.9.3`, I've just published it and it should become downloadable in < 15mins.

**Comment by diegoulloao** [comment]
Working!! Thank you

**Comment by diegoulloao** [comment]
What about the endpoint widget? Will be remain like it is?

**Comment by darrenburns** [comment]
For that I need to decide how to style it. For example if we choose the primary and accent, then we must ensure that they're readable against the background colour. I may need to specify in the docs that primary and accent must be readable against a background colour or something.

Or, I could add some extra variables to the theme, but that kind of goes against how the themes are currently expressed.

**Comment by darrenburns** [comment]
This is resolved in 1.10. The URL bar, variable highlighting, and JSON syntax highlighting will sample from the theme, and you can customise them using the theme file.

**Comment by darrenburns** [comment]
Without manually tweaking the highlighting, here's neofusion:

<img width="880" alt="image" src="https://github.com/user-attachments/assets/209543fe-ed67-42f9-8387-393b07492234">

**Comment by diegoulloao** [comment]
Looking really good! 🔥

**Comment by darrenburns** [comment]
Oh nice one :)

Out of curiosity, what do you use to capture terminal screenshots? They always look great!

**Comment by diegoulloao** [comment]
> Oh nice one :)
> 
> Out of curiosity, what do you use to capture terminal screenshots? They always look great!

Native macOS screenshot app 😂

**Comment by diegoulloao** [comment]
iTerm2 as terminal emulator for screenshots only. Kitty for personal use :)
