### ISSUE TITLE
Highlighter not visible in hacker theme

### ISSUE THREAD

**Issue by krishna-gujjjar** [darrenburns/posting#68]
I just switched to the `Hacker` theme, it look awesome but when i want expand response section and search for that the highlighted word not visible. 

> I search for `view` and it not highlighted in `Hacker` theme.

![Screenshot 2024-08-01 at 10 16 06 AM](https://github.com/user-attachments/assets/d57fed31-bb91-4b1b-9f21-12558f7cd1b9)

**Comment by darrenburns** [comment]
Thanks - I'll see if I can find something that works better for this.

**Comment by darrenburns** [comment]
This is fixed in Posting 2.2
