### ISSUE TITLE
Input Field in New Request Creation Popup Allows ~, Causing Error

### ISSUE THREAD

**Issue by Zimzozaur** [darrenburns/posting#82]
I tried to create a new request by typing ~/Desktop in the directory input field, which resulted in the following error:
```AddNodeError: The node specified for `after` is not a child of this node```

This input field should have stricter validation. I also entered ./test to create a folder in the default directory, but this caused the same error.

**Comment by darrenburns** [comment]
I've added extra validation in the new version `1.11.0`. Feel free to re-open if you're still having issues!

**Comment by Zimzozaur** [comment]
Nice! Now it works very elegantly!
