### ISSUE TITLE
Crash on creating request in non-existent directory

### ISSUE THREAD

**Issue by khaosdoctor** [darrenburns/posting#86]
If I try to create a new request and, in the `directory` field, put something different than `.` and this directory does not exist I get a huge stacktrace but it sums up to this error:

![image](https://github.com/user-attachments/assets/a75680fe-a1c3-4d4a-8007-99d24970a0bf)

**Comment by darrenburns** [comment]
Can you share what directory you put?

I think this is fixed in the upcoming release, but would appreciate if you can share the exact thing you wrote in the field.

**Comment by darrenburns** [comment]
Seems to be fixed on the new version, `1.11.0`. Feel free to re-open if you're still having issues!
