### ISSUE TITLE
Make keybindings configurable

### ISSUE THREAD

**Issue by diegodorado** [darrenburns/posting#95]
I know this might be a big ask, but my current issue is that a few useful keybindings like C-j and C-o in my case are already in use by my wezterm configuration.
While I could replace C-o with something else, C-j is what I use for pane navigation, and I can see how others using tmux-navigation or a zellij variation can suffer from this same problem.

To simplify the initial title, making C-j configurable would be enough to avoid commonly used terminal multiplexer navigation

Lovely tool by the way!

**Comment by diegodorado** [comment]
Oh, well... I also have C-s as my prefix, so that one is also colliding

**Comment by darrenburns** [comment]
Keys clashing with multiplexers and having no way around it really isn't great. I think I'll pull this near the top of the roadmap.

**Comment by diegodorado** [comment]
That is great, thanks! lmk if I can be of any help

**Comment by darrenburns** [comment]
I think we're planning to add this to the underlying framework (Textual) itself, so hopefully within the next couple of months it'll find its way into Posting.

**Comment by seapagan** [comment]
> Oh, well... I also have C-s as my prefix, so that one is also colliding

This is my issue too, Ctrl-S is a very common redefinition of the prefix key for Tmux users.

**Comment by vandaimer** [comment]
Is this something already working, no?

**Comment by darrenburns** [comment]
@vandaimer Yeah, it is. However, it's not as extensive as I'd like it to be yet.

**Comment by darrenburns** [comment]
I'm going to close this, as there are now a bunch of configurable bindings and I'm gradually adding more: https://posting.sh/guide/keymap/
