### ISSUE TITLE
Request "raw" Body Content-Type always `application/json`

### ISSUE THREAD

**Issue by naydichev** [darrenburns/posting#96]
Hello!

When I set the body type to `Raw (json, text, etc)`, I'm presented with another dropdown in the bottom right of that input box. From there I can choose `JSON, HTML or Text` - but regardless of which I choose, the content-type that is being sent is `application/json`.

Shouldn't `HTML` yield `text/html`, and `Text` => `text/plain` ?

I find that if I manually set the header in the `Headers` tab, then it's sent correctly - but it seems like it should be done automatically...

**Comment by darrenburns** [comment]
Yup, you're right. Should be fixed in v2 soon.
